spring: 
  profiles: 
  active: 
  - dev

---
spring: 
  profiles: dev   #开发环境
  application: 
    name: microservice-config-byf-dev

---
spring: 
  profiles: test  #测试环境
  application:
    name: microservice-config-byf-test

# 保存为UTF-8格式